[package]
name = "meshmon"
version = "0.3.0"
authors = ["Bart Noordervliet <bart@mmvi.nl>"]
edition = "2021"

[dependencies]
tokio = { version = "1", features = [ "full" ] }
toml = "0.5"
base64 = "0.13"
serde = "1"
serde_derive = "1"
rmp-serde = "1"
crypto_box = "0.8"
rand = "0.8"
byteorder = "1"
sysinfo = "0.26"
generic-array = "0.14"
petgraph = "0.6"
clap = "4"
pnet = "0"
warp = { version = "0.3", features = ["default", "tls"] }
lazy_static = "1"
tui = { version = "0.19", default-features = false, features = ['termion'] }
termion = "1"
chrono = "0.4"

[profile.release]
strip = true
#lto = "thin"
