[package]
name = "watcher"
version = "0.1.0"
authors = ["Bart Noordervliet <bart@mmvi.nl>"]
edition = "2018"

[dependencies]
tokio = { version = "1", features = [ "full" ] }
toml = "0.5"
base64 = "0.13"
serde = "1"
serde_derive = "1"
rmp-serde = "0.15"
crypto_box = "0.6"
rand = "0.8"
byteorder = "1"
sysinfo = "0.17"
generic-array = "0.14"
petgraph = "0.5"
