[package]
name = "watcher"
version = "0.1.0"
authors = ["Bart Noordervliet <bart@mmvi.nl>"]
edition = "2018"

[dependencies]
toml = "0.5"
serde = "1"
serde_derive = "1"
tokio = { version = "1", features = [ "full" ] }
crypto_box = "0.5"
rand = "0.7"
base64 = "0.13"
